title: Daniel & Gabby's Notebook
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://daniel-gabby-research.github.io

aux_links:
  Github: https://github.com/daniel-gabby-research/daniel-gabby-research.github.io
  Twitter: https://x.com/danielgabby
  LinkedIn: https://www.linkedin.com/in/daniel-gabby-research/

compress_html:
  blanklines: false


